### ISSUE TITLE
Bikeshedding the SDP parameter name

### ISSUE THREAD

**Issue by JonathanLennox** [juberti/cryptex#20]
I'm not 100% convinced that `extmap-encrypted` is the best name for the SDP parameter name -- the "map" part of the `extmap` parameter's signifies the mapping between extension IDs and extension URIs, which doesn't apply to the cryptex extension usage.

**Comment by juberti** [comment]
Makes sense. Have another suggestion? ```a=cryptex```?

**Comment by JonathanLennox** [comment]
Do we want to make cryptex a "real" protocol name?  If so, `a=cryptex` would be fine...

**Comment by juberti** [comment]
That was the list consensus.
