### ISSUE TITLE
Interaction with RFC 6904

### ISSUE THREAD

**Issue by bifurcation** [juberti/cryptex#32]
This document should specify how it interacts with RFC 6904 header encryption.  Is it legal for both of them to be applied to the same packet?  If so, which should be applied first?

**Comment by murillo128** [comment]
While there is no technical issue on having both rfc6904 and cryptex applied on the same rtp packet, it doesn't really make much sense. So my proposal would be to:

- Allow negotiation of both rfc6904 header extension encryption and cryptex
- If a packet is encrypted with cryptex it MUST NOT use rfc6904 header extension encryption.
