### ISSUE TITLE
Need reference vectors in spec for proper tests

### ISSUE THREAD

**Issue by juberti** [juberti/cryptex#7]

**Comment by murillo128** [comment]
We can use the test vectors created by @JonathanLennox in his jitsi PR which I have already added to the libsrtp PR and verified that are working perfectly.

We have a plaintext and encrypted results for: 
- a packet without csrcs or header extension (that should output the same as "normal" srtp)
- a packet with csrcs and a 0 length header extension (for both 1 and 2 bytes header extensions)
- a packet without csrcs and header extension (for both 1 and 2 bytes header extensions)
- a packet with csrcs and header extensions (for both 1 and 2 bytes header extensions)

in both aes-ctr and aes-gcm

AES-CTR ones:
https://github.com/cisco/libsrtp/blob/fbf23e29d30df59b1ce62809f0c1c3f4b2b99395/test/srtp_driver.c#L1821

AES-GCM ones:
https://github.com/cisco/libsrtp/blob/fbf23e29d30df59b1ce62809f0c1c3f4b2b99395/test/srtp_driver.c#L2291

I will create a PR for incorporating them into the spec.

**Comment by juberti** [comment]
Fixed by #21
