### ISSUE TITLE
[Paul Wouters] IPR

### ISSUE THREAD

**Issue by murillo128** [juberti/cryptex#74]
The Shepherds write-up with respect to IPR shows two authors confirming they
have filed "all required disclosures" but does not list whether this
means "there are non", "there are some, compatible with IETF" or that
there is "disclosed, incompatible with IETF". The Shepherds write up
does state no disclosures are filed. I find the two authors' response a
bit odd.

**Comment by aboba** [comment]
The authors have not filed any IPR disclosures. The status of the non-author IPR disclosures is here: https://mailarchive.ietf.org/arch/msg/avt/c88xDocWibCpJntwzj0rYG-3lfk/
