### ISSUE TITLE
[Zaheduzzaman Sarker] IPR

### ISSUE THREAD

**Issue by murillo128** [juberti/cryptex#91]
the shepherd's write-up says there is not IPR declarations but https://datatracker.ietf.org/ipr/search/?submit=draft&id=draft-ietf-avtcore-cryptex return two hits on IPR declarations. The write up should be updated, was the WG not aware of these IPRs?

**Comment by aboba** [comment]
The WG was notified of the IPR declaration in email and it was also brought up in the May 2022 interim meeting. Details are here: 
https://mailarchive.ietf.org/arch/msg/avt/c88xDocWibCpJntwzj0rYG-3lfk/
